### ISSUE TITLE
Status and plans

### ISSUE THREAD

**Issue by emoon** [Squirrel/squirrel-rs#6]
Hi,

I'm working on a application that I would like to provide auto-updates to my users with (also written in Rust) and I support Mac, Linux and Windows.

I wonder what the current status of this crate is and what the plans are for the future?

**Comment by anaisbetts** [comment]
Mostly a research project atm, sorry. For at least Windows, Squirrel.Windows today supports any application type. Squirrel.Mac is a little harder, and for Linux, you have to use the system distro's updater
